//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GJP_IMIS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sarah Marie M. Jalandoon")]
        public string dtr_Signee1_Name {
            get {
                return ((string)(this["dtr_Signee1_Name"]));
            }
            set {
                this["dtr_Signee1_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLSO II")]
        public string dtr_Signee1_Position {
            get {
                return ((string)(this["dtr_Signee1_Position"]));
            }
            set {
                this["dtr_Signee1_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rowell C. Mangibin")]
        public string dtr_Signee2_Name {
            get {
                return ((string)(this["dtr_Signee2_Name"]));
            }
            set {
                this["dtr_Signee2_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSO II / Intern Coordinator")]
        public string dtr_Signee2_Position {
            get {
                return ((string)(this["dtr_Signee2_Position"]));
            }
            set {
                this["dtr_Signee2_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maria Vida G. Caparas, Ph.D., RPsy")]
        public string letter_Signee_Name {
            get {
                return ((string)(this["letter_Signee_Name"]));
            }
            set {
                this["letter_Signee_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Director III")]
        public string letter_Signee_Position {
            get {
                return ((string)(this["letter_Signee_Position"]));
            }
            set {
                this["letter_Signee_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maria Vida G. Caparas, Ph.D., RPsy")]
        public string cert_Signee_Name {
            get {
                return ((string)(this["cert_Signee_Name"]));
            }
            set {
                this["cert_Signee_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Director III")]
        public string cert_Signee_Position {
            get {
                return ((string)(this["cert_Signee_Position"]));
            }
            set {
                this["cert_Signee_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Human Resource Management Services")]
        public string cert_Signee_Office {
            get {
                return ((string)(this["cert_Signee_Office"]));
            }
            set {
                this["cert_Signee_Office"] = value;
            }
        }
    }
}
